// Generated by CoffeeScript 1.7.1
var app, bodyParser, cors, mongoose;

cors = require('cors');

app = require('express')();

bodyParser = require('body-parser');

app.use(cors({
  origin: true,
  credentials: true
}));

app.use(bodyParser.json());

mongoose = require('mongoose');

mongoose.connect('mongodb://localhost/typeset', function(err) {
  var io, server;
  if (err) {
    console.log('MongoDB connection failed!');
  } else {
    console.log('MongoDB Connected!');
    server = app.listen(8888, function() {
      return console.log('Listening on port ' + 8888);
    });
    io = require('socket.io')(server);
    io.on('connection', function(socket) {
      console.log('New Socket Connected!');
      require('./lib/doc')(socket, mongoose);
      return socket.on('disconnect', function(socket) {
        return console.log('Socket Disconnected!');
      });
    });
    app.post('/research', function(req, res) {
      var Document, docid;
      docid = req.param('docid');
      Document = require('./lib/models/Document')(mongoose);
      return Document.findOne({
        _id: docid
      }, function(err, document) {
        var docSock;
        if (err || !document) {
          return res.json({
            code: 400,
            error: 'Invalid Document'
          });
        } else {
          docSock = io.of('/' + docid);
          docSock.on('connection', function(socket) {
            console.log('Socket connected for document: ' + docid);
            return require('./lib/research/editor')(socket, mongoose);
          });
          return res.json({
            code: 200
          });
        }
      });
    });
  }
});

//# sourceMappingURL=index.map
