// Generated by CoffeeScript 1.7.1
angular.module('ts', ['docbrowser', 'ui.router', 'socket']);

angular.module('ts').config([
  '$stateProvider', '$urlRouterProvider', function($stateProvider, $urlRouterProvider) {
    $urlRouterProvider.otherwise('/');
    return $stateProvider.state('docs', {
      url: '/',
      templateUrl: 'components/docbrowser/browser.html',
      controller: 'DocbrowserController'
    });
  }
]);

angular.module('ts').run([
  'SocketService', function(SocketService) {
    return SocketService.connect();
  }
]);

//# sourceMappingURL=app_module.map
