// Generated by CoffeeScript 1.7.1
angular.module('ts.util').directive('placeFocus', [
  '$timeout', function($timeout) {
    return {
      restrict: 'A',
      link: function(scope, element) {
        return $timeout(function() {
          return element.focus();
        });
      }
    };
  }
]);

//# sourceMappingURL=placefocus.map
