// Generated by CoffeeScript 1.7.1
angular.module('socket', []);

angular.module('socket').factory('SocketService', [
  '$q', function($q) {
    var connect, disconnect, storage;
    storage = {
      socket: null
    };
    connect = function(docid) {
      var deferred;
      if (docid == null) {
        docid = null;
      }
      deferred = $q.defer();
      console.log('[SocketService]: Connecting...' + docid);
      if (!storage.socket) {
        if (docid) {
          storage.socket = io.connect('http://localhost:8888/' + docid);
        } else {
          storage.socket = io.connect('http://localhost:8888');
        }
        storage.socket.on('connect', function() {
          console.log('[SocketService]: Connected ' + docid);
          return deferred.resolve();
        });
        storage.socket.on('connect_error', function(err) {
          console.log('[SocketService]: Connection Error ' + docid);
          return console.log(err);
        });
      }
      return deferred.promise;
    };
    disconnect = function() {
      var _ref;
      if ((_ref = storage.socket) != null) {
        _ref.disconnect();
      }
      storage.socket = null;
    };
    return {
      connect: connect,
      disconnect: disconnect,
      socket: function() {
        return storage.socket;
      }
    };
  }
]);

//# sourceMappingURL=socket.map
