// Generated by CoffeeScript 1.7.1
angular.module('ts.util').factory('UUIDFactory', [
  function() {
    var _generateShortUUID, _generateUUID;
    _generateShortUUID = function() {
      return ("0000" + (Math.random() * Math.pow(36, 4) << 0).toString(36)).substr(-4);
    };
    _generateUUID = function() {
      var d, uuid;
      d = new Date().getTime();
      uuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
        var r, _ref;
        r = (d + Math.random() * 16) % 16 | 0;
        d = Math.floor(d / 16);
        return ((_ref = c === 'x') != null ? _ref : {
          r: r & 0x7 | 0x8
        }).toString(16);
      });
      return uuid;
    };
    return {
      generateShortUUID: _generateShortUUID,
      generateUUID: _generateUUID
    };
  }
]);

//# sourceMappingURL=uuid.map
