// Generated by CoffeeScript 1.7.1
var listeners;

listeners = {};

module.exports.on = function(eventName, listener) {
  if (!listeners.hasOwnProperty(eventName)) {
    listeners[eventName] = [];
  }
  console.log('Attaching event listener to ' + eventName);
  return listeners[eventName].push(listener);
};

module.exports.offAll = function() {
  listeners = {};
};

module.exports.invoke = function(eventName, data, done) {
  var doneCount, listener, _i, _len, _ref, _results, _results1;
  doneCount = 0;
  _results = [];
  if (listeners.hasOwnProperty(eventName)) {
    _ref = listeners[eventName];
    _results1 = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      listener = _ref[_i];
      _results1.push(listener(data, function(result) {
        doneCount += 1;
        _results.push(result);
        if (doneCount === listeners[eventName].length) {
          return done(_results);
        }
      }));
    }
    return _results1;
  } else {
    return done([]);
  }
};

//# sourceMappingURL=socket.map
