// Generated by CoffeeScript 1.7.1
var Delta;

Delta = null;

module.exports = function(mongoose) {
  var DeltaSchema;
  if (!Delta) {
    DeltaSchema = new mongoose.Schema({
      document: mongoose.Schema.Types.ObjectId,
      name: String,
      timestamp: {
        type: Date,
        "default": Date.now
      },
      args: mongoose.Schema.Types.Mixed
    });
    Delta = mongoose.model('Delta', DeltaSchema);
  }
  return Delta;
};

//# sourceMappingURL=Delta.map
