// Generated by CoffeeScript 1.7.1
angular.module('research', ['ui.router', 'socket', 'delta', 'ts.util', 'monospaced.elastic']);

angular.module('research').config([
  '$stateProvider', '$urlRouterProvider', function($stateProvider, $urlRouterProvider) {
    $urlRouterProvider.otherwise('/');
    return $stateProvider.state('edit', {
      url: '/',
      templateUrl: 'components/research/editor.html',
      controller: 'ResearchEditorController'
    });
  }
]);

//# sourceMappingURL=research_module.map
