// Generated by CoffeeScript 1.7.1
module.exports = function(socket, mongoose) {
  var Delta, Document;
  Document = require('./models/Document')(mongoose);
  Delta = require('./models/Delta')(mongoose);
  socket.on('doc.list', function(data, response) {
    console.log('[Doc]: Listing...');
    return Document.find({}).sort({
      createdAt: -1
    }).exec(function(err, result) {
      if (err) {
        response({
          code: 500,
          error: 'Error fetching documents'
        });
      } else {
        response({
          code: 200,
          data: result
        });
      }
    });
  });
  socket.on('doc.create', function(data, response) {
    var document;
    console.log('[Doc]: Creating...');
    document = new Document({
      name: data.name
    });
    return document.save(function(err) {
      if (err) {
        response({
          code: 500,
          error: 'Error creating new document'
        });
      } else {
        response({
          code: 200,
          data: document
        });
      }
    });
  });
  socket.on('doc.rename', function(data, response) {
    console.log('[Doc]: Renaming...');
    return Document.update({
      _id: data.id
    }, {
      name: data.name
    }, function(err) {
      if (err) {
        response({
          code: 500,
          error: 'Failed to update the title'
        });
      } else {
        response({
          code: 200
        });
      }
    });
  });
  return socket.on('doc.delete', function(data, response) {
    console.log('[Doc]: Deleting...');
    return Document.remove({
      _id: data.id
    }, function(err) {
      if (err) {
        response({
          code: 500,
          error: 'Could not delete document'
        });
      } else {
        Delta.remove({
          document: data.id
        }, function(err) {
          if (err) {
            return response({
              code: 500,
              error: 'Could not delete document'
            });
          } else {
            return response({
              code: 200
            });
          }
        });
      }
    });
  });
};

//# sourceMappingURL=doc.map
