// Generated by CoffeeScript 1.7.1
module.exports = function(socket, mongoose, document) {
  var Delta, saveDelta;
  Delta = require('./models/Delta')(mongoose);
  saveDelta = function(delta, response) {
    delta.save(function(err) {
      if (err) {
        response({
          code: 500,
          error: 'Error saving delta'
        });
      } else {
        response({
          code: 200
        });
      }
    });
  };
  socket.on('section.add', function(data, response) {
    var delta, index, section_id;
    section_id = data.section_id;
    index = data.index;
    delta = new Delta({
      document: document._id,
      name: 'section.add',
      args: {
        section_id: section_id,
        index: index
      }
    });
    return saveDelta(delta, response);
  });
  socket.on('section.delete', function(data, response) {
    var delta, section_id;
    section_id = data.section_id;
    delta = new Delta({
      document: document._id,
      name: 'section.delete',
      args: {
        section_id: section_id
      }
    });
    return saveDelta(delta, response);
  });
  socket.on('subsection.add', function(data, response) {
    var delta, index, section_id, subsection_id;
    section_id = data.section_id;
    subsection_id = data.subsection_id;
    index = data.index;
    delta = new Delta({
      document: document._id,
      name: 'subsection.add',
      args: {
        section_id: section_id,
        subsection_id: subsection_id,
        index: index
      }
    });
    return saveDelta(delta, response);
  });
  return socket.on('subsection.delete', function(data, response) {
    var delta, section_id, subsection_id;
    section_id = data.section_id;
    subsection_id = data.subsection_id;
    delta = new Delta({
      document: document._id,
      name: 'subsection.delete',
      args: {
        section_id: section_id,
        subsection_id: subsection_id
      }
    });
    return saveDelta(delta, response);
  });
};

//# sourceMappingURL=research-editor.map
