// Generated by CoffeeScript 1.7.1
angular.module('delta').factory('DeltaService', [
  'SocketService', '$http', '$q', function(SocketService, $http, $q) {
    var _addDelta, _connect, _storage, _sync;
    _storage = {
      nextIdxToSync: 0,
      deltas: [],
      syncing: false,
      connected: false
    };
    _sync = function() {
      var delta, _ref;
      _storage.syncing = true;
      delta = _storage.deltas[_storage.nextIdxToSync];
      return (_ref = SocketService.socket()) != null ? _ref.emit(delta.name, delta.args, function(response) {
        if (response.code === 200) {
          _storage.deltas[_storage.nextIdxToSync].synced = true;
          _storage.nextIdxToSync += 1;
          if (_storage.deltas.length > _storage.nextIdxToSync) {
            return _sync();
          } else {
            _storage.syncing = false;
            return console.log('[DeltaService]: All Synced!');
          }
        } else {
          throw new Error('[DeltaService]: SyncFailure!');
        }
      }) : void 0;
    };
    _connect = function(doctype, docid) {
      var deferred;
      deferred = $q.defer();
      console.log('[DeltaService]: Requesting namespace ' + docid);
      $http.post('http://localhost:8888/' + doctype, {
        docid: docid
      }).then(function(response) {
        var document;
        console.log(response);
        if (response.data.code === 200) {
          document = response.data.data;
          console.log('[DeltaService]: Setting up the socket connection...');
          return SocketService.connect(docid).then(function() {
            console.log('[DeltaService]: Connected');
            return deferred.resolve(document);
          }, function() {
            console.log('[DeltaService]: Failed to connect!');
            return deferred.reject();
          });
        } else {
          console.log('[DeltaService]: Failed to establish namespace');
          return deferred.reject('Failed to connect');
        }
      }, function(error) {
        console.log('[DeltaService]: Error: Failed to establish namespace');
        return deferred.reject(error);
      });
      return deferred.promise;
    };
    _addDelta = function(delta) {
      console.log('[DeltaService]: Adding Delta...');
      delta.synced = false;
      _storage.deltas.push(delta);
      if (!_storage.syncing) {
        return _sync();
      }
    };
    return {
      storage: _storage,
      connect: _connect,
      addDelta: _addDelta
    };
  }
]);

//# sourceMappingURL=delta.map
